---
- name: "Install pip"
  apt:
    name: python3-pip

- name: "Install docker python module"
  pip:
    name: docker

- name: "Build cocalc docker image"
  docker_image:
    name: sagemathinc/cocalc

- name: "Set up cocalc docker containter"
  docker_container:
    image: sagemathinc/cocalc
    name: cocalc
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/home/ansible/cocalc:/projects"
      - "/home/ansible/cc_run:/run"
    keep_volumes: true

- name: "apt update in docker container"
  shell: "docker exec cocalc apt-get update"

- name: "Install full texlive"
  shell: "docker exec -e DEBIAN_FRONTEND=noninteractive cocalc apt-get install -y texlive-full"

- name: "Create certificate directory"
  file:
    path: "/home/ansible/cc_run/.well-known"
    state: directory

- name: "Create acme-challenge directory"
  file:
    path: "/home/ansible/cc_run/acme-challenge"
    state: directory

- name: "Create certificate directory symlinks"
  file:
    path: "/home/ansible/cc_run/.well-known/acme-challenge"
    src: "/home/ansible/cc_run/acme-challenge/"
    state: link
